version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
    - 8080:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  php:
    image: php:7.2-fpm
    volumes:
      - ./src:/usr/share/nginx/html
