version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 8888:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build: ./php
    links:
      - mysql 
    volumes:
      - ./src:/usr/share/nginx/html

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: roots
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8183:80
    links:
      - mysql:db
      

      